In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import pickle as pkl
from sklearn.model_selection  import train_test_split

In [2]:
book = pd.read_csv("Books.csv")
ratin = pd.read_csv("Ratings.csv")
user= pd.read_csv("Users.csv")

C:\Users\vivek\AppData\Local\Temp\ipykernel_15372\3371696119.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv("Books.csv")

In [3]:
book.sample()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
214294,0140130187,Souls &amp; Bodies (King Penguin),David Lodge,1989,Penguin Books,http://images.amazon.com/images/P/0140130187.0...,http://images.amazon.com/images/P/0140130187.0...,http://images.amazon.com/images/P/0140130187.0...

In [4]:
books = book.drop(["Image-URL-S", "Image-URL-M","Image-URL-L"],axis=1)

In [5]:
books.sample(5)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
207164,0670868035,With Custer on the Little Bighorn: A Newly Dis...,William O. Taylor,1996,Viking Books
223286,3150181305,Troia: Mythos und Wirklichkeit (Universal-Bibl...,Michael Siebler,2001,Reclam
177771,0006176747,Medusa,Hammond Innes,0,Fontana Paperbacks
96515,0060266686,In the Night Kitchen (Caldecott Collection),Maurice Sendak,1996,HarperCollins
195312,0553226754,Chill,Ross MacDonald,1983,Bantam Books

In [6]:
books = books.rename(columns={'Book-Title':'name','Book-Author':'author','Year-Of-Publication':'year','publisher':'Publisher'})

In [7]:
books

,ISBN,name,author,year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm)
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages

In [8]:
rating=ratin.rename(columns={'User-ID':'id','Book-Rating':'rating'})

In [9]:
rating.groupby('ISBN').count()

             id  rating
ISBN
 0330299891   2       2
 0375404120   2       2
 0586045007   1       1
 9022906116   2       2
 9032803328   1       1
...          ..     ...
cn113107      1       1
ooo7156103    1       1
§423350229    1       1
´3499128624   1       1
Ô½crosoft     1       1

[340556 rows x 2 columns]

In [10]:
user.sample()

      User-ID                       Location  Age
9857     9858  pittsburgh, pennsylvania, usa  NaN

In [12]:
user=user.rename(columns={'User-ID':'id','Location':'location','Age':'age'})

In [13]:
x =rating['id'].value_counts() > 200

In [14]:
y=x[x].index

In [15]:
rating=rating[rating['id'].isin(y)]

In [16]:
rating.shape

(526356, 3)

In [17]:
rating_with_books=rating.merge(books,on='ISBN')

In [18]:
rating_with_books.shape

(487671, 7)

In [19]:
rating_with_books[rating_with_books['rating'].isin(y)]

Empty DataFrame
Columns: [id, ISBN, rating, name, author, year, Publisher]
Index: []

In [126]:
number_rating=rating_with_books.groupby('name')['rating'].count().reset_index()

In [128]:
number_rating=number_rating.rename(columns={'rating':'num_rating'})

In [129]:
final_rating=rating_with_books.merge(number_rating,on='name')

In [130]:
final_rating.shape

(487671, 8)

In [131]:
final_rating=final_rating[final_rating['num_rating'] >= 50 ]

In [132]:
final_rating

,id,ISBN,rating,name,author,year,Publisher,num_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,79
...,...,...,...,...,...,...,...,...
487505,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,84
487506,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,60
487579,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,59
487618,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,146
487619,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,53

In [133]:
final_rating.drop_duplicates(['id','name'], keep='first',inplace=True)

In [134]:
final_rating.shape

(59850, 8)

In [135]:
final_rating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59850 entries, 0 to 487619
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          59850 non-null  int64
 1   ISBN        59850 non-null  object
 2   rating      59850 non-null  int64
 3   name        59850 non-null  object
 4   author      59850 non-null  object
 5   year        59850 non-null  object
 6   Publisher   59850 non-null  object
 7   num_rating  59850 non-null  int64
dtypes: int64(3), object(5)
memory usage: 4.1+ MB

In [136]:
book_pivot=final_rating.pivot_table(columns='id',index='name',values='rating')

In [137]:
book_pivot.shape

(742, 888)

In [138]:
book_pivot.fillna(0,inplace=True)

In [139]:
book_pivot

id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
name,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(book_pivot)

In [35]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [36]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm = 'brute')

In [37]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [38]:
distances, suggestions = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [39]:
for i in suggestions: 
    print(book_pivot.index[i])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='name')

In [40]:
distances[0][1].dtype

dtype('float64')

In [197]:
def recommonend_book(book_name):
    book_id = np.where(book_pivot.index==book_name)[0][0]
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)
    for i in range(len(suggestions)):
        print(book_pivot.index[suggestions[i][1:]].tolist())

In [204]:
recommonend_book('Harry Potter and the Goblet of Fire (Book 4)')

['Harry Potter and the Prisoner of Azkaban (Book 3)', 'Harry Potter and the Order of the Phoenix (Book 5)', 'Harry Potter and the Chamber of Secrets (Book 2)', 'The Cradle Will Fall', 'Exclusive']

In [43]:
pkl.dump(model,open('model_book.pkl','wb'))

In [44]:
pkl.dump(recommonend_book,open('output_book.pkl','wb'))

In [45]:
book_pivot.to_csv('book_pivot.csv')

In [46]:
book.to_csv('final_books.csv')

In [47]:
book=book[['Book-Title','Image-URL-M']].rename(columns={'Book-Title':'name','Image-URL-M':'poster'})

In [154]:
book.drop_duplicates()

,name,poster
0,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...
...,...,...
271355,There's a Bat in Bunk Five,http://images.amazon.com/images/P/0440400988.0...
271356,From One to One Hundred,http://images.amazon.com/images/P/0525447644.0...
271357,Lily Dale : The True Story of the Town that Ta...,http://images.amazon.com/images/P/006008667X.0...
271358,Republic (World's Classics),http://images.amazon.com/images/P/0192126040.0...
271359,A Guided Tour of Rene Descartes' Meditations o...,http://images.amazon.com/images/P/0767409752.0...

In [348]:
book[book['name']=="Republic (World's Classics)"]['poster'].values[0]

'http://images.amazon.com/images/P/0192126040.01.MZZZZZZZ.jpg'

In [349]:
book['poster'].isnull().sum()

np.int64(0)

In [351]:
book[book['name']== 'Jacob Have I Loved']['poster']

7702     http://images.amazon.com/images/P/0380564998.0...
8395     http://images.amazon.com/images/P/0590434985.0...
13005    http://images.amazon.com/images/P/0064403688.0...
51793    http://images.amazon.com/images/P/0690040784.0...
80739    http://images.amazon.com/images/P/0690040792.0...
92413    http://images.amazon.com/images/P/0064470598.0...
Name: poster, dtype: object

In [390]:
("http://images.amazon.com/images/P/0192126040.01.MZZZZZZZ.jpg").split('http')

['', '://images.amazon.com/images/P/0192126040.01.MZZZZZZZ.jpg']

In [383]:
list[0] = 'https'

In [389]:
"".join(list)

'https://images.amazon.com/images/P/0192126040.01.MZZZZZZZ.jpg'

In [393]:
def change(value):
    list = value.split('http')
    list[0]='https'
    return "".join(list)

In [395]:
book['poster']=book['poster'].apply(change)

In [49]:
book

,name,poster
0,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...
...,...,...
271355,There's a Bat in Bunk Five,http://images.amazon.com/images/P/0440400988.0...
271356,From One to One Hundred,http://images.amazon.com/images/P/0525447644.0...
271357,Lily Dale : The True Story of the Town that Ta...,http://images.amazon.com/images/P/006008667X.0...
271358,Republic (World's Classics),http://images.amazon.com/images/P/0192126040.0...
271359,A Guided Tour of Rene Descartes' Meditations o...,http://images.amazon.com/images/P/0767409752.0...

In [184]:
book.drop_duplicates()

,name,poster
0,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...
...,...,...
271355,There's a Bat in Bunk Five,http://images.amazon.com/images/P/0440400988.0...
271356,From One to One Hundred,http://images.amazon.com/images/P/0525447644.0...
271357,Lily Dale : The True Story of the Town that Ta...,http://images.amazon.com/images/P/006008667X.0...
271358,Republic (World's Classics),http://images.amazon.com/images/P/0192126040.0...
271359,A Guided Tour of Rene Descartes' Meditations o...,http://images.amazon.com/images/P/0767409752.0...

In [185]:
df =rating.merge(books.drop('year',axis=1),on='ISBN')

In [187]:
final_books=book.merge(df,on='name').drop_duplicates('name').drop(['id','ISBN','rating'],axis=1).sort_values('name')

In [189]:
final_books

,name,poster,author,Publisher
335993,A Light in the Storm: The Civil War Diary of ...,http://images.amazon.com/images/P/0590567330.0...,Karen Hesse,Hyperion Books for Children
871288,Always Have Popsicles,http://images.amazon.com/images/P/0964147726.0...,Rebecca Harvin,Rebecca L. Harvin
650336,Apple Magic (The Collector's series),http://images.amazon.com/images/P/0942320093.0...,Martina Boudreau,Amer Cooking Guild
262279,Beyond IBM: Leadership Marketing and Finance ...,http://images.amazon.com/images/P/0962295701.0...,Lou Mobley,"Teleonet, Incorporated"
802539,Clifford Visita El Hospital (Clifford El Gran...,http://images.amazon.com/images/P/0439188970.0...,Norman Bridwell,Scholastic
...,...,...,...,...
681232,Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...,http://images.amazon.com/images/P/3257700512.0...,Henry David Thoreau,Diogenes
687039,Ã?Â?lpiraten.,http://images.amazon.com/images/P/3499232499.0...,Janwillem van de Wetering,Rowohlt Tb.
469798,Ã?Â?rger mit Produkt X. Roman.,http://images.amazon.com/images/P/325721538X.0...,Joan Aiken,Diogenes Verlag
568532,Ã?Â?stlich der Berge.,http://images.amazon.com/images/P/3442725739.0...,David Guterson,btb
380556,Ã?Â?thique en toc,http://images.amazon.com/images/P/2842192508.0...,Didier Daeninckx,Baleine

In [190]:
final_books.to_csv('finalbooks.csv')

In [252]:
def recommend_book(book_name):
        book_id = np.where(book_pivot.index == book_name)[0][0]
        distances, suggestions = model.kneighbors(
            book_pivot.iloc[book_id, :].values.reshape(1, -1),
            n_neighbors=6
        )
        recommended_books = []
        for i in suggestions[0]:
            recommended_books.append(book_pivot.index[i])
        return recommended_books[1:]

book_name = 'Harry Potter and the Chamber of Secrets (Book 2)'
list = recommend_book(book_name)

poster_list=[]
name_list=[]
author_list=[]
publser_list=[]
for book in list:
        poster = final_books[final_books['name'] == book]['poster'].values[0]
        name = final_books[final_books['name'] == book]['name'].values[0]
        author = final_books[final_books['name'] == book]['author'].values[0]
        publisher = final_books[final_books['name'] == book]['Publisher'].values[0]
        poster_list.append(poster)
        name_list.append(name)
        author_list.append(author)
        publser_list.append(publisher)
print(name_list)

['Harry Potter and the Goblet of Fire (Book 4)', 'Harry Potter and the Prisoner of Azkaban (Book 3)', "Harry Potter and the Sorcerer's Stone (Book 1)", 'Exclusive', 'The Cradle Will Fall']

In [220]:
np.where(book_pivot.index =='Harry Potter and the Chamber of Secrets (Book 2)')

(array([237]),)

In [262]:
pd.read_csv('book_pivot.csv',index_col=0).index.tolist()

['1984',
 '1st to Die: A Novel',
 '2nd Chance',
 '4 Blondes',
 '84 Charing Cross Road',
 'A Bend in the Road',
 'A Case of Need',
 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 'A Civil Action',
 'A Cry In The Night',
 'A Darkness More Than Night',
 'A Day Late and a Dollar Short',
 'A Fine Balance',
 'A Great Deliverance',
 'A Heartbreaking Work of Staggering Genius',
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 'A Man Named Dave: A Story of Triumph and Forgiveness',
 'A Man in Full',
 'A Map of the World',
 'A Painted House',
 'A Patchwork Planet',
 'A Prayer for Owen Meany',
 'A Thin Dark Line (Mysteries &amp; Horror)',
 "A Thousand Acres (Ballantine Reader's Circle)",
 'A Time to Kill',
 "A Virtuous Woman (Oprah's Book Club (Paperback))",
 'A Walk to Remember',
 'A Widow for One Year',
 'A Wrinkle In Time',
 'A Wrinkle in Time',
 'A Year in Provence',
 "ANGELA'S ASHES",
 'Abduction',
 'About a Boy',
 'Absolute Power',
 'Acceptable Risk',
 'Accident',
 'Airframe',
 'Alaska',
 'All Around the Town',
 'All Creatures Great and Small',
 'All I Really Need to Know',
 'All That Remains (Kay Scarpetta Mysteries (Paperback))',
 'All the Pretty Horses (The Border Trilogy, Vol 1)',
 'Along Came a Spider (Alex Cross Novels)',
 'American Gods',
 'And Then You Die',
 "Angela's Ashes (MMP) : A Memoir",
 "Angela's Ashes: A Memoir",
 'Angels',
 'Angels &amp; Demons',
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
 'Animal Dreams',
 'Animal Farm',
 'Anne Frank: The Diary of a Young Girl',
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
 'Anne of the Island',
 'Artemis Fowl (Artemis Fowl, Book 1)',
 'Ashes to Ashes',
 'At Home in Mitford (The Mitford Years)',
 'Atonement : A Novel',
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
 'Back Roads',
 'Bag of Bones',
 'Balzac and the Little Chinese Seamstress : A Novel',
 'Bastard Out of Carolina',
 'Beach House',
 'Beach Music',
 'Before I Say Good-Bye',
 'Bel Canto: A Novel',
 'Beloved',
 'Beloved (Plume Contemporary Fiction)',
 'Betrayal in Death',
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'Big Trouble',
 'Billy Straight : A Novel',
 'Birthright',
 'Bittersweet',
 'Black House',
 'Black Notice',
 'Black and Blue',
 'Bleachers',
 'Blessings',
 'Blood Work',
 'Blue Diary',
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
 'Body of Lies',
 'Brave New World',
 'Breath, Eyes, Memory',
 'Breathing Lessons',
 'Bridge to Terabithia',
 'Bridget Jones : The Edge of Reason',
 "Bridget Jones's Diary",
 'Bridget Jones: The Edge of Reason',
 'By the Light of the Moon',
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
 "CAT'S EYE",
 'Call of the Wild',
 'Carnal Innocence',
 'Carolina Moon',
 'Carrie',
 'Cat &amp; Mouse (Alex Cross Novels)',
 'Catering to Nobody',
 'Cause of Death',
 'Certain Prey',
 "Charlotte's Web (Trophy Newbery)",
 'Charming Billy',
 'Chicken Soup for the Soul (Chicken Soup for the Soul)',
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
 'Chocolat',
 'Choke',
 'Chosen Prey',
 'Christine',
 'Chromosome 6',
 'Circle of Friends',
 'Clear and Present Danger (Jack Ryan Novels)',
 'Cold Mountain',
 'Cold Mountain : A Novel',
 'Cold Sassy Tree',
 'Colony',
 'Coming Home',
 'Confessions of a Shopaholic (Summer Display Opportunity)',
 'Confessions of an Ugly Stepsister : A Novel',
 'Congo',
 'Contact',
 'Contagion',
 'Coraline',
 'Couplehood',
 'Cradle and All',
 'Crazy for You',
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
 'Cry Wolf',
 'Cujo',
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
 'Daddy',
 "Daddy's Little Girl",
 'Daisy Fay and the Miracle Man',
 'Dance upon the Air (Three Sisters Island Trilogy)',
 'Dances With Wolves',
 'Dangerous',
 'Dark Angel',
 'Dark Paradise',
 'Dark Rivers of the Heart',
 'Dawn (Cutler)',
 'Dead Run',
 'Death du Jour',
 'Debt of Honor (Jack Ryan Novels)',
 'Deception Point',
 'Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure',
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dolores Claiborne',
 "Don't Stand Too Close to a Naked Man",
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
 "Dr. Atkins' New Diet Revolution",
 'Dragon Tears',
 'Dragonfly in Amber',
 'Dream Country',
 'Dreamcatcher',
 'Drowning Ruth',
 "Drowning Ruth (Oprah's Book Club)",
 'Drums of Autumn',
 "Dude, Where's My Country?",
 'Dust to Dust',
 'Dying for Chocolate (Culinary Mysteries (Paperback))',
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
 'Easy Prey',
 'Echoes',
 'Ellen Foster',
 'Empire Falls',
 "Ender's Game (Ender Wiggins Saga (Paperback))",
 'Engaging The Enemy',
 'Envy',
 'Evening Class',
 "Everything's Eventual : 14 Dark Tales",
 'Exclusive',
 'Executive Orders (Jack Ryan Novels)',
 'Eyes of Prey',
 'Eyes of a Child',
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
 'FORREST GUMP (Movie Tie in)',
 'Face the Fire (Three Sisters Island Trilogy)',
 'Fahrenheit 451',
 'Faking It',
 'Fall On Your Knees (Oprah #45)',
 'Falling Angels',
 'False Memory',
 'Family Album',
 'Fast Food Nation: The Dark Side of the All-American Meal',
 'Fast Women',
 'Fat Tuesday',
 'Fatal Cure',
 'Fatherhood',
 'Fear Nothing',
 'Final Target',
 'Fine Things',
 'Fingersmith',
 'Five Days in Paris',
 'Five Quarters of the Orange',
 'Flesh and Blood',
 'Forever... : A Novel of Good and Evil, Love and Hope',
 "Fortune's Rocks : A Novel",
 "Fortune's Rocks: A Novel",
 "Foucault's Pendulum",
 'Four Blind Mice',
 'Four Past Midnight',
 'Four To Score (A Stephanie Plum Novel)',
 'Fried Green Tomatoes at the Whistle Stop Cafe',
 "From Potter's Field",
 'From the Corner of His Eye',
 "Full House (Janet Evanovich's Full Series)",
 "Full Tilt (Janet Evanovich's Full Series)",
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))',
 "Gerald's Game",
 'Girl in Hyacinth Blue',
 'Girl with a Pearl Earring',
 'Girl, Interrupted',
 'Good Omens',
 'Good in Bed',
 'Gorky Park',
 'Granny Dan',
 'Guardian Angel',
 'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
 'Guilty as Sin',
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
 'Hannibal',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Harvest',
 'Heart of the Sea (Irish Trilogy)',
 'Heartbeat',
 'Heartbreaker',
 'Hearts In Atlantis',
 'Hearts in Atlantis',
 'Heaven and Earth (Three Sisters Island Trilogy)',
 'Hemlock Bay',
 'Here on Earth',
 'Hide &amp; Seek',
 'Hideaway',
 'High Fidelity',
 'High Five (A Stephanie Plum Novel)',
 'Holes (Yearling Newbery)',
 'Homecoming',
 'Homeport',
 "Hornet's Nest",
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'House of Sand and Fog',
 'How Stella Got Her Groove Back',
 'How to Be Good',
 'How to Make an American Quilt',
 'I Capture the Castle',
 'I Is for Innocent',
 'I Know This Much Is True',
 "I Know This Much Is True (Oprah's Book Club)",
 'I Know Why the Caged Bird Sings',
 "I'll Be Seeing You",
 'Icebound',
 'Icy Sparks',
 'If Only It Were True',
 'If Tomorrow Comes',
 'Impulse',
 'In Her Shoes : A Novel',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'Insomnia',
 'Intensity',
 'Interview with the Vampire',
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
 'Into the Wild',
 'Invasion',
 'Irish Hearts',
 'Isle of Dogs',
 'It',
 'It Was on Fire When I Lay Down on It',
 "It's Always Something",
 'J Is for Judgment',
 'Jack &amp; Jill (Alex Cross Novels)',
 'Jacob Have I Loved',
 'Jemima J: A Novel About Ugly Ducklings and Swans',
 'Jewel',
 "Jewel (Oprah's Book Club)",
 'Jewels of the Sun (Irish Trilogy)',
 'Journey',
 'Jurassic Park',
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
 'Kaleidoscope',
 'Key of Knowledge (Key Trilogy (Paperback))',
 'Key of Light (Key Trilogy (Paperback))',
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)',
 'Killjoy',
 'Kiss the Girls',
 'L Is for Lawless',
 'Ladder of Years',
 'Lake Wobegon Days',
 'Lake Wobegon days',
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
 'Last Chance Saloon',
 'Last Man Standing',
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
 'Let Me Call You Sweetheart',
 'Life of Pi',
 'Lightning',
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
 'Little Altars Everywhere: A Novel',
 'Long After Midnight',
 'Lord of the Flies',
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
 'Loves Music, Loves to Dance',
 'Lucky : A Memoir',
 'Lucky Man: A Memoir',
 'M Is for Malice',
 'Macgregor Brides (Macgregors)',
 'Macgregor Grooms (Macgregors)',
 'Master of the Game',
 'Matilda',
 'Me Talk Pretty One Day',
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
 'Mercy',
 'Message from Nam',
 'Message in a Bottle',
 'Middlesex: A Novel',
 'Midnight',
 'Midnight Bayou',
 'Midnight in the Garden of Good and Evil',
 'Midnight in the Garden of Good and Evil: A Savannah Story',
 'Midwives: A Novel',
 'Mind Prey',
 'Mirror Image',
 'Misery',
 'Miss Julia Speaks Her Mind : A Novel',
 'Monster : A Novel (Alex Delaware Novels (Paperback))',
 'Montana Sky',
 'Moo',
 'Moonlight Becomes You',
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
 'Mortal Fear',
 'Mortal Prey',
 'Mother of Pearl',
 'Mr. Murder',
 'My Gal Sunday',
 'Mystic River',
 'N Is for Noose',
 'Naked',
 'Needful Things',
 'Nerd in Shining Armor',
 'Neuromancer (Remembering Tomorrow)',
 'Neverwhere',
 'Nickel and Dimed: On (Not) Getting By in America',
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)',
 'Night',
 'Night Prey',
 'Night Sins',
 'Night Whispers',
 'Nightmares &amp; Dreamscapes',
 'Nights in Rodanthe',
 'No Greater Love',
 'No Safe Place',
 'Notes from a Small Island',
 'Nothing Lasts Forever',
 'Now You See Her',
 'On the Street Where You Live',
 'One Door Away from Heaven',
 'One True Thing',
 'One for the Money (A Stephanie Plum Novel)',
 'One for the Money (Stephanie Plum Novels (Paperback))',
 'Oryx and Crake',
 'Outlander',
 'Over the Edge',
 'P Is for Peril',
 'Paradise',
 'Patriot Games (Jack Ryan Novels)',
 'Pay It Forward',
 'Peace Like a River',
 'Pet Sematary',
 'Phantoms',
 'Pigs in Heaven',
 'Plainsong (Vintage Contemporaries)',
 'Pleading Guilty',
 'Plum Island',
 'Point of Origin',
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
 'Pop Goes the Weasel',
 'Portrait in Death',
 'Possession : A Romance',
 'Postmortem',
 'Practical Magic',
 'Presumed Innocent',
 "Pretend You Don't See Her",
 'Pride and Prejudice',
 'Primary Colors: A Novel of Politics',
 'Prime Cut',
 'Prodigal Summer',
 'Prodigal Summer: A Novel',
 'Purity in Death',
 'Q Is for Quarry',
 'Quentins',
 'Rainbow Six',
 'Range of Motion',
 'Reap the Wind',
 'Rebecca',
 'Red Dragon',
 'Red Storm Rising',
 'Remember Me',
 'Riptide',
 'Rising Sun',
 'Rising Tides',
 "River's End",
 'River, Cross My Heart',
 'Rose Madder',
 'Roses Are Red (Alex Cross Novels)',
 'Rules of Prey',
 'SHIPPING NEWS',
 'STONES FROM THE RIVER',
 'Sacred Sins',
 'Saint Maybe',
 'Sanctuary',
 'Saving Faith',
 'Scarlet Feather',
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
 "Schindler's List",
 'Sea Glass: A Novel',
 'Sea Swept (Quinn Brothers (Paperback))',
 'Seabiscuit',
 'Seabiscuit: An American Legend',
 'Second Nature',
 'Secret History',
 'Secrets',
 'Seize the Night',
 'September',
 'Seven Habits Of Highly Effective People',
 'Seven Up (A Stephanie Plum Novel)',
 'Shadow Prey',
 'Shadowfires',
 'Shattered',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 "She's Come Undone (Oprah's Book Club)",
 'Shell Seekers',
 'Shopaholic Takes Manhattan (Summer Display Opportunity)',
 'Shopaholic Ties the Knot',
 'Sick Puppy',
 'Silence of the Lambs',
 'Silent Witness',
 'Sisterhood of the Traveling Pants',
 'Skeleton Crew',
 'Skipping Christmas',
 'Slammerkin',
 "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
 'Sleepers',
 'Slow Waltz in Cedar Bend',
 'Small Town Girl',
 'Smart Women',
 "Smilla's Sense of Snow",
 'Snow Falling on Cedars',
 'Sole Survivor',
 "Song of Solomon (Oprah's Book Club (Paperback))",
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
 "Sophie's World: A Novel About the History of Philosophy",
 'Southern Cross',
 'Sphere',
 'Standoff',
 'Stanislaski Brothers (Silhouette Promo)',
 'Still Waters',
 'Stillwatch',
 'Strangers',
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
 'Sudden Prey',
 'Summer Pleasures',
 'Summer Sisters',
 "Suzanne's Diary for Nicholas",
 'Table For Two',
 'Tales of a Fourth Grade Nothing',
 'Taltos: Lives of the Mayfair Witches',
 'Tara Road',
 'Tears of the Giraffe (No.1 Ladies Detective Agency)',
 'Tears of the Moon (Irish Trilogy)',
 'Tell Me Lies (Tell Me Lies)',
 'Tell Me Your Dreams',
 'Tell No One',
 'Temptation',
 'That Camden Summer',
 'The Accidental Tourist',
 'The Alchemist: A Fable About Following Your Dream',
 'The Alibi',
 'The Alienist',
 'The Amazing Adventures of Kavalier &amp; Clay',
 'The Amber Spyglass (His Dark Materials, Book 3)',
 'The Andromeda Strain',
 'The Angel of Darkness',
 'The Apprentice',
 'The Bachelor (Warner Books Contemporary Romance)',
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
 'The Bad Place',
 'The Beach House',
 'The Bean Trees',
 'The Blind Assassin',
 'The Blue Nowhere : A Novel',
 'The Bluest Eye',
 'The Body Farm',
 "The Bonesetter's Daughter",
 'The Bonfire of the Vanities',
 "The Book of Ruth (Oprah's Book Club (Paperback))",
 'The Bourne Identity',
 'The Bourne Supremacy',
 'The Bourne Ultimatum',
 'The Boy Next Door',
 'The Brethren',
 'The Bridges of Madison County',
 'The Burden of Proof',
 'The Cardinal of the Kremlin (Jack Ryan Novels)',
 'The Carousel',
 'The Catcher in the Rye',
 'The Celestine Prophecy (Celestine Prophecy)',
 'The Chamber',
 'The Cider House Rules',
 "The Clan of the Cave Bear (Earth's Children (Paperback))",
 'The Client',
 'The Clinic (Alex Delaware Novels (Paperback))',
 'The Color Purple',
 "The Color of Water: A Black Man's Tribute to His White Mother",
 'The Copper Beech',
 'The Cradle Will Fall',
 'The Crimson Petal and the White',
 'The Da Vinci Code',
 'The Dark Half',
 'The Dead Zone',
 'The Deep End of the Ocean',
 'The Devil Wears Prada : A Novel',
 'The Diary of Ellen Rimbauer: My Life at Rose Red',
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'The Dogs of Babel (Today Show Book Club #12)',
 'The Door to December',
 'The Drawing of the Three (The Dark Tower, Book 2)',
 'The Edge',
 'The Eight',
 'The Empty Chair',
 'The English Patient',
 'The Eyre Affair: A Novel',
 'The Face of Deception',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Firm',
 'The First Counsel',
 'The First Wives Club Movie Tie In',
 'The Five People You Meet in Heaven',
 'The Fourth Hand',
 "The General's Daughter",
 'The Genesis Code',
 'The Ghost',
 'The Gift',
 'The Girl Who Loved Tom Gordon',
 "The Girls' Guide to Hunting and Fishing",
 'The Giver (21st Century Reference)',
 'The Glass Lake',
 'The God of Small Things',
 'The Golden Compass (His Dark Materials, Book 1)',
 'The Great Gatsby',
 'The Green Mile',
 'The Grilling Season',
 'The Guardian',
 'The Gunslinger (The Dark Tower, Book 1)',
 "The Handmaid's Tale",
 "The Hitchhiker's Guide to the Galaxy",
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
 'The Honk and Holler Opening Soon',
 'The Horse Whisperer',
 'The Hot Zone',
 'The Hours : A Novel',
 'The Hours: A Novel',
 'The House of the Spirits',
 'The Hundred Secret Senses',
 'The Hunt for Red October',
 "The Idiot Girls' Action Adventure Club",
 'The Jester',
 'The Joy Luck Club',
 'The Killing Game: Only One Can Win...and the Loser Dies',
 'The King of Torts',
 'The Kiss',
 "The Kitchen God's Wife",
 'The Last Precinct',
 'The Last Time They Met : A Novel',
 'The Little Friend',
 'The Little Prince',
 'The Long Road Home',
 'The Loop',
 "The Lost Boy: A Foster Child's Search for the Love of a Family",
 'The Lost World',
 'The Lottery Winner : Alvirah And Willy Stories',
 'The Lovely Bones: A Novel',
 'The Mists of Avalon',
 'The Most Wanted',
 'The Mulberry Tree',
 'The Mummy or Ramses the Damned',
 'The Murder Book',
 'The Nanny Diaries: A Novel',
 'The Next Accident',
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
 'The Notebook',
 'The Other Boleyn Girl',
 'The Partner',
 'The Pelican Brief',
 'The Perfect Storm : A True Story of Men Against the Sea',
 'The Phantom Tollbooth',
 'The Pillars of the Earth',
 "The Pilot's Wife : A Novel",
 "The Plains of Passage (Earth's Children (Paperback))",
 'The Poisonwood Bible',
 'The Poisonwood Bible: A Novel',
 'The Prince of Tides',
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
 'The Promise',
 'The Pull of the Moon',
 'The Queen of the Damned (Vampire Chronicles (Paperback))',
 'The Rainmaker',
 'The Rapture of Canaan',
 'The Reader',
 'The Red Tent (Bestselling Backlist)',
 'The Reef',
 'The Regulators',
 'The Reptile Room (A Series of Unfortunate Events, Book 2)',
 'The Rescue',
 'The Return Journey',
 'The Return of the King (The Lord of the Rings, Part 3)',
 'The Robber Bride',
 'The Runaway Jury',
 'The Sands of Time',
 'The Saving Graces: A Novel',
 'The Search',
 'The Secret Garden',
 'The Secret Life of Bees',
 'The Shining',
 'The Shipping News : A Novel',
 'The Simple Truth',
 'The Smoke Jumper',
 'The Stone Diaries',
 'The Street Lawyer',
 'The Subtle Knife (His Dark Materials, Book 2)',
 'The Sum of All Fears (Jack Ryan Novels)',
 'The Summerhouse',
 'The Summons',
 'The Surgeon',
 "The Sweet Potato Queens' Book of Love",
 'The Switch',
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
 'The Talisman',
 'The Tao of Pooh',
 'The Temple of My Familiar',
 'The Terminal Man',
 'The Testament',
 'The Thorn Birds',
 'The Tommyknockers',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Ugly Duckling',
 'The Valley of Horses',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'The Villa',
 'The Virgin Suicides',
 'The Wedding',
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion',
 'The Winner',
 'The Witching Hour (Lives of the Mayfair Witches)',
 'The Witness',
 'The Woman Next Door',
 'Thinner',
 'Three Fates',
 'Three Junes',
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Timeline',
 'Tis : A Memoir',
 'Tis: A Memoir',
 'To Kill a Mockingbird',
 'To the Nines: A Stephanie Plum Novel',
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
 'Touching Evil',
 'Tough Cookie',
 'Toxin',
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',